### ISSUE TITLE
How can Pumpfun use 'pump' as the suffix in their contract address?

### ISSUE THREAD

**Issue by WSbaikaishui** [rckprtr/pumpdotfun-sdk#10]
I would like to know how they achieved that. Did they use brute force to generate the key pairs?

like 6M8LqJNAah3fDG5TwH6opCbeDVKa51nXLG5VkZAHpump

**Comment by rckprtr** [comment]
They pre-grind them using this: https://www.quicknode.com/guides/solana-development/getting-started/how-to-create-a-custom-vanity-wallet-address-using-solana-cli

and then on create token the frontend queries the next available one and assigns it to the mint.

**Comment by WSbaikaishui** [comment]
thanks, it's helpful for me

**Comment by AndreaZero** [comment]
> They pre-grind them using this: https://www.quicknode.com/guides/solana-development/getting-started/how-to-create-a-custom-vanity-wallet-address-using-solana-cli
> 
> and then on create token the frontend queries the next available one and assigns it to the mint.

They don't to like that. Imagine for every token created searching for 'pump'at the suffis? It will take YEARS. 

How does pump.fun have "pump"at the end of their Contract Address?

Account Derivation (PDAs - Program Derived Addresses) in Solana

Program Derived Addresses (PDAs) are special types of addresses in Solana that are generated deterministically using a program’s public key and custom seeds (like strings such as "pump", hashes, or other unique data). Unlike regular Solana addresses, PDAs are not associated with a private key, meaning they can only be controlled by the specific program that derived them.

How PDAs Work:
Deterministic Generation:
PDAs are created using a combination of:

A program ID (the public key of the smart contract)
One or more seed values (strings, hashes, user-specific data, etc.)
Cryptographic Functions:
The address derivation uses Solana's findProgramAddress function, which applies a hashing algorithm (SHA-256) to the program ID and the seeds. This ensures the resulting PDA is unique and deterministic—meaning the same inputs always produce the same PDA.

Non-Signable Addresses:
Since PDAs don’t have corresponding private keys, they cannot sign transactions. Instead, Solana allows the program itself to "authorize" actions on behalf of the PDA using program logic.

**Comment by rckprtr** [comment]
Awesome, I didnt know, I was curious if it was possible to sniff the key returned and change the meta data, but I guess not...
