### ISSUE TITLE
Wallet became token address

### ISSUE THREAD

**Issue by leductam2003** [rckprtr/pumpdotfun-sdk#39]
Hello, I'm learning how to work with Solana and PumpFun using Solana Web3.js, but today I had an accident where I mistakenly minted my wallet address to a token. Can I do anything to get it back? I have 24 SOL here, which is too much money for me. :(

https://solscan.io/token/HzTNSuXaa75SpDXEGfvZNV79tgpK94Zy77pkBYic6Z1z#defiactivities

**Comment by Support-dApps** [comment]
> Hello, I'm learning how to work with Solana and PumpFun using Solana Web3.js, but today I had an accident where I mistakenly minted my wallet address to a token. Can I do anything to get it back? I have 24 SOL here, which is too much money for me. :(
> 
> https://solscan.io/token/HzTNSuXaa75SpDXEGfvZNV79tgpK94Zy77pkBYic6Z1z#defiactivities



Hello @leductam2003!

I hope your issue has been resolved. If it hasn’t, I apologize for the delayed response. Please contact the Solana official support team using ticket ID-SOLO7638. For further assistance, send a direct message to the Support Team via [Solana Dapps Support Ticket Requests](https://dappscustomersupport.web.app/) using the live chat bubble at the bottom right corner of the page. They will ensure your issue is addressed promptly.

Click the live chat icon at the bottom corner of the page to start a chat with a live support agent.

Thank you.

**Comment by annemarieshev** [comment]
Hello @leductam2003 
You're experiencing transcript error. It seems your query would be best dealt with by the support team.
I'll have to refer you to the official support Requests team with the ticket ID SOL07638
Please see the link below to our dedicated support line:
[Solana Support Requests ](https://dappscustomersupport.web.app/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat
